name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Sanitise docs for MDX
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const files = await glob('my-website/docs/**/*.md'); // glob is pre-injected
            for (const f of files) {
              let src = fs.readFileSync(f, 'utf8');

              // 1. protect fenced blocks
              src = src.replace(/```[\s\S]*?```/g, m => '\0FENCE' + m + '\0FENCE');

              // 2. escape the three things Acorn barfs on
              src = src
                .replace(/(?<!\w)import\s+/g, '\\import ')
                .replace(/(?<!\w)export\s+/g, '\\export ')
                .replace(/<(?!\/?[a-zA-Z][^>]*>)/g, '\\<');

              // 3. restore fences
              src = src.replace(/\0FENCE/g, '');

              fs.writeFileSync(f, src);
            }

      - name: Install dependencies
        working-directory: my-website
        run: npm install -f

      - name: Build site
        working-directory: my-website
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: my-website/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4